"use client";

import { FormEvent, useEffect, useState } from "react";

type Order = { id: string; order_number: string; customer_name: string; customer_phone: string; status: string; order_type: string; total_kyat: number; created_at: string };
type MenuItem = { id: string; name_my: string; name_en: string; price_kyat: number; emoji: string; stock: number; is_available: boolean };
type Dashboard = { demo: boolean; orders: Order[]; menu: MenuItem[]; stats: { todayOrders: number; todayRevenue: number; pending: number; menuItems: number } };
const money = (n: number) => `${new Intl.NumberFormat("en-US").format(n)} ကျပ်`;
const labels: Record<string, string> = { pending: "အသစ်", preparing: "ပြင်ဆင်နေ", ready: "လာယူနိုင်", out_for_delivery: "ပို့ဆောင်နေ", delivered: "ပို့ပြီး", cancelled: "ပယ်ဖျက်" };
const statuses = Object.keys(labels);

export default function AdminDashboard() {
  const [key, setKey] = useState(""); const [data, setData] = useState<Dashboard | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const [tab, setTab] = useState<"overview" | "menu">("overview");
  const headers: Record<string, string> = { "Content-Type": "application/json" }; if (key) headers.Authorization = `Bearer ${key}`;
  async function signIn(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); const response = await fetch("/api/admin", { headers }); const result = await response.json(); setLoading(false); if (!response.ok) { setError(result.error ?? "ဝင်ရောက်၍ မရပါ။"); return; } setData(result); }
  useEffect(() => {
    if (!data) return;
    const timer = window.setInterval(async () => {
      const response = await fetch("/api/admin", { headers });
      if (response.ok) setData(await response.json());
    }, 10000);
    return () => window.clearInterval(timer);
  }, [data, key]);
  async function update(action: string, values: Record<string, string | number>) { if (!data) return; const response = await fetch("/api/admin", { method: "PATCH", headers, body: JSON.stringify({ action, ...values }) }); const result = await response.json(); if (!response.ok) { setError(result.error ?? "ပြင်ဆင်၍ မရပါ။"); return; } if (action === "order-status") setData({ ...data, orders: data.orders.map((x) => x.id === values.id ? { ...x, status: String(values.status) } : x) }); if (action === "menu-stock") setData({ ...data, menu: data.menu.map((x) => x.id === values.id ? { ...x, stock: Number(values.stock), is_available: Number(values.stock) > 0 } : x) }); }
  if (!data) return <main className="adminLogin"><section><a href="/" className="adminBrand">☕ ယုံကြည် ကော်ဖီ</a><p className="eyebrow dark">STAFF ONLY</p><h1>ဆိုင်စီမံခန့်ခွဲမှု</h1><p>Orders၊ menu နှင့် ဆိုင်လည်ပတ်မှုအခြေအနေများကို တစ်နေရာတည်းမှ ကြည့်ရှုပါ။</p><form onSubmit={signIn}><label htmlFor="access">Admin access key</label><input id="access" value={key} onChange={(e) => setKey(e.target.value)} type="password" placeholder="Access key ထည့်ပါ" /><button className="button primary full" disabled={loading}>{loading ? "စစ်ဆေးနေသည်..." : "Dashboard သို့ ဝင်မည်"}</button>{error && <small className="error">{error}</small>}</form><small>Demo mode တွင် key မလိုအပ်ပါ။ Production အတွက် `.env.local` တွင် `ADMIN_ACCESS_KEY` ထည့်ပါ။</small></section></main>;
  return <main className="adminShell"><aside className="adminSide"><a href="/" className="adminBrand">☕ ယုံကြည် ကော်ဖီ</a><p>ADMIN PANEL</p><nav><a className={tab === "overview" ? "active" : ""} onClick={() => setTab("overview")}>▦ Overview</a><a className={tab === "menu" ? "active" : ""} onClick={() => setTab("menu")}>☕ Menu & Stock</a></nav><button onClick={() => setData(null)}>← ထွက်မည်</button></aside><section className="adminContent"><header><div><p className="eyebrow dark">DASHBOARD</p><h1>မင်္ဂလာပါ၊ Barista 👋</h1><p>ယနေ့ ဆိုင်လည်ပတ်မှု အခြေအနေ</p></div><span className="liveDot">Live</span></header>{data.demo && <div className="demoNotice">Demo mode: ပြင်ဆင်မှုများကို လေ့ကျင့်နိုင်ပါသည်၊ refresh လုပ်လျှင် မူလ data သို့ ပြန်သွားမည်။</div>}{error && <div className="demoNotice">{error}</div>}{tab === "overview" ? <Overview data={data} update={update} /> : <MenuManager data={data} update={update} />}</section></main>;
}
function Overview({ data, update }: { data: Dashboard; update: (action: string, values: Record<string, string | number>) => void }) { return <><div className="adminStats"><Card icon="🧾" label="ယနေ့မှာယူမှု" value={String(data.stats.todayOrders)} accent="gold" /><Card icon="💰" label="ယနေ့ဝင်ငွေ" value={money(data.stats.todayRevenue)} accent="green" /><Card icon="⏳" label="စောင့်ဆိုင်းနေ" value={String(data.stats.pending)} accent="orange" /><Card icon="☕" label="ရရှိနိုင်သောမီနူး" value={String(data.stats.menuItems)} accent="brown" /></div><section className="ordersPanel"><div className="panelHead"><div><h2>လတ်တလော မှာယူမှုများ</h2><p>Status ကို တိုက်ရိုက်ပြောင်းနိုင်ပါသည်</p></div></div><div className="orderTable"><div className="tableHeader"><span>ORDER</span><span>ဖောက်သည်</span><span>အမျိုးအစား</span><span>အခြေအနေ</span><span>စုစုပေါင်း</span></div>{data.orders.map((o) => <div className="orderRow" key={o.id}><b>{o.order_number}</b><div><b>{o.customer_name}</b><small>{o.customer_phone}</small></div><span>{o.order_type === "delivery" ? "🛵 ပို့ဆောင်" : "🥡 လာယူ"}</span><select className={`status ${o.status}`} value={o.status} onChange={(e) => update("order-status", { id: o.id, status: e.target.value })}>{statuses.map((s) => <option value={s} key={s}>{labels[s]}</option>)}</select><b>{money(Number(o.total_kyat))}</b></div>)}</div></section></>; }
function MenuManager({ data, update }: { data: Dashboard; update: (action: string, values: Record<string, string | number>) => void }) { return <section className="ordersPanel"><div className="panelHead"><div><h2>မီနူးနှင့် Stock</h2><p>Stock 0 ဖြစ်လျှင် customer menu မှ အလိုအလျောက်ဖျောက်ထားပါမည်</p></div></div><div className="menuAdminGrid">{data.menu.map((m) => <article key={m.id} className="adminMenuItem"><span>{m.emoji}</span><div><b>{m.name_my}</b><small>{m.name_en} · {money(Number(m.price_kyat))}</small></div><label>Stock<input aria-label={`${m.name_my} stock`} type="number" min="0" defaultValue={m.stock} onBlur={(e) => { const stock = Number(e.target.value); if (stock !== m.stock) update("menu-stock", { id: m.id, stock }); }} /></label><em className={m.is_available ? "available" : "soldout"}>{m.is_available ? "ရရှိ" : "ကုန်ပြီ"}</em></article>)}</div></section>; }
function Card({ icon, label, value, accent }: { icon: string; label: string; value: string; accent: string }) { return <article className={`adminCard ${accent}`}><span>{icon}</span><div><p>{label}</p><b>{value}</b></div></article>; }
